### ISSUE TITLE
Clarify what this repo is and its package name

### ISSUE THREAD

**Issue by vmx** [ipld/js-ipld#112]
This repo got renamed from `js-ipld-resolver` to just `js-ipld`. What should the description say?

The GitHub description is: "JavaScript implementation of the IPLDService"
The package.json description is: "IPLD Resolver Implementation in JavaScript"
The Readme description is: "The JavaScript implementation of the IPLD, InterPlanetary Linked-Data"

I guess all should be the same.

This repo currently is published as [`ipld-resolver`](https://www.npmjs.com/package/ipld-resolver). @diasdavid mentions in https://github.com/ipld/js-ipld/pull/110#issuecomment-361006440 that this package should be deprecated an republished as just `ipld`.

Though the [`ipld` npm package](https://www.npmjs.com/package/ipld) currently points to https://github.com/diasdavid/js-ipld which currently redirects to https://github.com/ipld/js-ipld-dag-cbor.

And then there's also the [`ipfs-ipld` npm package](https://www.npmjs.com/package/ipfs-ipld) which points to https://github.com/ipfs/js-ipfs-ipld which redirects to https://github.com/ipld/js-ipld.

**Comment by vmx** [comment]
For the whole npm business I propose:

- The `ipld` package will be what is currently in this repository. Just override whatever is currently there if that's possible. This might break a lot of things.
- Deprecate the `ipld-resolver` package and add a warning that it is now named `ipld`
- Deprecate the `ipfs-ipld` package and add a warning that it is now named `ipld`

**Comment by vmx** [comment]
In regards to the description: I tried to find out what an "IPLD Service" is. It think the name would match this repository quite well, but I'm not sure if it already has some other meaning.

I'm not sure if naming a concept (IPLD) and the implementation the same is a good idea. That would be the case with "The JavaScript implementation of the IPLD". If we go with "IPLD Service" one could say "The JavaScript IPLD Service is an implementation of IPLD". And if you have discussion about the implementation, you can always say "IPLD Service" to make sure you mean the implementation.

**Comment by vmx** [comment]
As I tried to nail all this down, I looked at the Go side of things. There the corresponding repository https://github.com/ipfs/go-ipld is deprecated. Isn't there an equivalent? Is go-ipfs using the IPLD formats directly without another layer in between?

**Comment by mkg20001** [comment]
I think "IPLD Api" would be a good name because without bitswap the IPLD module isn't really a service

**Comment by diasdavid** [comment]
Oh wow, what a long turn -- https://www.npmjs.com/package/ipld --. @dignifiedquire can you give me and @vmx perms to that package? 

@vmx that package was created when the world thought that IPLD was CBOR.. (circa 2016)

**Comment by dignifiedquire** [comment]
> @vmx that package was created when the world thought that IPLD was CBOR.. (circa 2016)

ahh simpler times :)

**Comment by diasdavid** [comment]
@vmx, from @dignifiedquire:
```
> npm owner ls ipld
daviddias <daviddias.p@gmail.com>
vmx <volker.mische@gmail.com>
```

**Comment by vmx** [comment]
So we publish this one as version 1.0.0 under the new name?

**Comment by diasdavid** [comment]
We are still in the below 1.0.0 mode for IPFS modules until the whole IPFS protocol becomes 1.0.0 itself.

**Comment by vmx** [comment]
Yes for  sure, but replacing an existing package sounds to me like a mega-breaking change. Anyway, I'll let you sort this out, you know the JS ecosystem better than me.

**Comment by diasdavid** [comment]
@vmx js-ipld never got used and it doesn't really work for anything right now. The 286 Installs are all probably from CIs going through the registry :)

**Comment by diasdavid** [comment]
@vmx I feel that this is now clear to everyone, closing but reopen if you feel a different way.

**Comment by vmx** [comment]
@diasdavid Parts of the original issue is still not resolved. The Github description, the README and the package.json should have the same description. Currently they all say something different.

**Comment by diasdavid** [comment]
All the same now \o/ :)
