### ISSUE TITLE
Can we get a new release soon and update js-ipld on js-ipfs?

### ISSUE THREAD

**Issue by diasdavid** [ipld/js-ipld#116]
Is this possible, @vmx? For the js-ipfs 0.28 release?

**Comment by vmx** [comment]
@diasdavid Feel free to do a release (or if you want, I can also do the release). It would be under the current name `js-ipld-resolver`. Let's target proper naming and description (https://github.com/ipld/js-ipld/issues/112) for the next release.

**Comment by diasdavid** [comment]
@vmx why not deprecate the old name and release with the new name?

**Comment by vmx** [comment]
@diasdavid: If we can sort out #112 that's fine for me.

**Comment by diasdavid** [comment]
@vmx I believe you have everything you need from https://github.com/ipld/js-ipld/issues/112#issuecomment-367770576

**Comment by vmx** [comment]
@diasdavid So I should just change the package name name and publish a 0.28 under the new name?

**Comment by diasdavid** [comment]
@vmx exactly and then deprecate ipld-resolver with the message to use just ipld.

**Comment by diasdavid** [comment]
And of course, updating it in js-ipfs-unixfs-engine and js-ipfs too :)

**Comment by vmx** [comment]
I don't know if there's any guidelines for deprecation messages. What a about using this one:

> WARNING: This project has been renamed to "ipld". Install using "ipld" instead.

**Comment by vmx** [comment]
Sorry, I should've closed #93 and not this one. This one needs more work (and code changes on other packages).

**Comment by vmx** [comment]
@diasdavid The js-ipfs-unixfs-engine update will take a bit as currently some tests fail: https://github.com/ipfs/js-ipfs-unixfs-engine/issues/203

**Comment by diasdavid** [comment]
thanks @vmx, just incorporated your fixes, updated deps and released js-ipfs-unixfs-engine \o/

**Comment by vmx** [comment]
Almost there https://github.com/ipfs/js-ipfs-unixfs-engine/pull/206

**Comment by diasdavid** [comment]
got it. Confused with the refactor on js-ipfs which I also merged :) Thanks for being on top of things!

**Comment by vmx** [comment]
@diasdavid If you do another js-ipfs-unixfs-engine release, I think we are ready to go from an js-ipld perspective. One there's a new release of js-ipfs I'll deprecate js-ipld-resolver.

**Comment by vmx** [comment]
All packages that depended on ipld-resolver (https://github.com/ipfs/js-ipfs, https://github.com/ipfs/js-ipfs-unixfs-engine) switched to just "ipld". I will close this issue when I deprecated `js-ipld-resolver`, which I will do once https://github.com/ipfs/js-ipfs is releases. Else people will get deprecation messages during installation.

**Comment by vmx** [comment]
I can't deprecate ipld-resolver:

```
$ npm deprecate ipld-resolver@'<= 0.14.1' 'WARNING: This project has been renamed to "ipld". Install using "ipld" instead.'
npm ERR! code E422
npm ERR! Unprocessable Entity : ipld-resolver

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vmx/.npm/_logs/2018-03-02T13_06_01_826Z-debug.log
```

**Comment by diasdavid** [comment]
@vmx have you reached out to npm support?

**Comment by vmx** [comment]
@diasdavid No I haven't, I thought I'm doing something wrong.

**Comment by diasdavid** [comment]
@vmx have you tried just with `npm deprecate ipld-resolver@0.14.1`?

**Comment by vmx** [comment]
@diasdavid Yes, also without version and putting the quotes around the name and version.
