### ISSUE TITLE
Implement `isLink()`

### ISSUE THREAD

**Issue by vmx** [ipld/js-ipld#126]
The `isLink()` function was removed from the IPLD Format spec (https://github.com/ipld/interface-ipld-format/pull/23), in favour of putting this functionality into js-ipld instead.

The [implementation from js-ipld-dag-pb](https://github.com/ipld/js-ipld-dag-pb/blob/40a5e65d8089fa88dc42498e8b00712906bf3712/src/resolver.js#L115-L143) can be used.

**Comment by jonahweissman** [comment]
I'd like to tackle this, if that's okay.

**Comment by jonahweissman** [comment]
So, it looks like `isLink()`, as implemented in js-ipld-dag-pb, accepts a binary blob, and then uses `resolve()` to  find the link corresponding to the given path. However, in js-ipld, the function equivalent to `resolve()` seems to be `get()`, which accepts a CID. Would it be better to try to determine the CID from the binary blob, or just change `isLink()` to take a CID as an argument?

It's also quite possible there's something I'm missing. I'm still trying to get a sense of how all these pieces fit together.

**Comment by jonahweissman** [comment]
To clarify my question a bit: if `isLink()` operates on binaryblobs, how do we know which resolver to use?

**Comment by vmx** [comment]
The more I think about it, the more i wonder if `isLink()` is actually a useful thing. What is its use case?

Things that came to my mind, but where there are better solutions:

 - You don't  know the structure of the node and you want to explore it: In this case I'd expect that you want the other contents as well, so you'd call (on the format level) `resolve('/')`.
 - You want to traverse the DAG: Then you probably know the structure of the node and you don't want to traverse any link, but a specific one. So you know that it is a a link and don't need `isLink()`.

@jonahweissman @olizilla @mikeal @diasdavid @Stebalien Can you think of cases where you'd want to have an `isLink()` function?

**Comment by mikeal** [comment]
I can't think of a great case because the path resolver stops at a link and links are easy to identify as the return value, especially if we move to using CID instances.

However, I could definitely see a use for either a `links` method that returned all links and/or a `tree` option that noted which paths were links.

**Comment by vmx** [comment]
I'm closing this issue as "won't fix". Having a `isLink()` method is not really useful.

@jonahweissman Thanks for looking into this and getting the discussion started.
