### ISSUE TITLE
ENAMETOOLONG Error

### ISSUE THREAD

**Issue by osarrouy** [ipld/js-ipld#130]
Hey,

I'm currently trying to create a new IPLD format resolver. It works fine, however a strange thing happen ... Sometime, when the object i'm trying to push is "too" long i got the following when a I call the ```put``` method:
```
Error: ENAMETOOLONG: name too long, open '/Users/osarrouy/Documents/devs/dapps/@wespr/pando/test/mocks/.pando/ipfs/blocks/J6/AFKRXWIBPMREA5DZOBSSEORCONXGC4DTNBXXIIRMEJQXK5DIN52HI4RCHIRDEZBUO5UGM2TLNBRGM43ENNVGM2DTNJSGW2BCFQRHI5BCHIRDEZBUO5UGM2TLNBRGM43ENNVGMZDTMZZWIZTEONTWMZTEM5SGMZ3EON5GM2DTNJSGW2BCFQRG2ZLTONQWOZJCHIRFIZLTOQQHG3TBOBZWQ33UEIWCE4DBOJSW45DTEI5FWXJMEJ2HEZLFEI5HWIRPEARDUITUN52G6IT5FQRHI2LNMVTWIZTIM5UHG5DBNVYCEORCPJXXU332N55G66TPPJXXU332N55G66TPPJXXU332N55G66T2EJ6Q.data.301414793'
```

That's really weird because the length of the block file seems linked to the 'length' of the object - and seems to exceed the limit of the filesystem.

It happens on macOS with a resolver whose serialization method is just a ```Buffer.from(JSON.stringify(dagNode))```

Any idea ?

**Comment by vmx** [comment]
@osarrouy It would be super helpful if you could provide a test/small script reproducing this error. This way someone can more easily have a look.

Just a note, IPLD nodes have a limit of 2MB, though I'm not sure where that is actually enforced.

**Comment by osarrouy** [comment]
@vmx I'm gonna try to make a gist to reproduce the steps.

**Comment by osarrouy** [comment]
@vmx In fact it raises the same error each time your try to ```put``` a buffer which is more than than 145 long - i.e. its OK a 145 but throws a 146 - with the ```keccak-256``` hashAlgorithm. Do you think it may come from a bug in the keccak-256 CID implementation ?

**Comment by vmx** [comment]
@osarrouy I don't have any instant idea. Please also note that the next 2.5 weeks I won't have much time to look into it (hence I tried to get the other PR out before that). So feel free to dig deeper yourself :)

**Comment by osarrouy** [comment]
@vmx Ok. I'm gonna try to figure it out. I let you know if i find something.

**Comment by osarrouy** [comment]
Hey @vmx,

It seems the problem came from the ```multihashes``` library I use in my resolver to compute the multihash of the CID and which produced oooooooverly long hashes - like 2000 bytes long for keccak-256 -_- 

Everything works fine using the ```multihashing-async```library.

So the problem is not ```js-ipld``` related but ```multihashes``` related.

**Comment by vmx** [comment]
As the last comment mentions it's not `js-ipld` related, hence closing this issue. Feel free to re-open if you disagree.
