### ISSUE TITLE
feat: .get(<array of CIDs>)

### ISSUE THREAD

**Issue by diasdavid** [ipld/js-ipld#132]
We need an endpoint for https://github.com/ipfs/js-ipfs-unixfs-engine that can return multiple IPLD nodes from an Array of CIDs.

Leverage https://github.com/ipfs/js-ipfs-block-service/pull/81

This is blocking https://github.com/ipfs/js-ipfs/pull/856.

@vmx do you already have code for this with the GraphSync endeavour?

**Comment by vmx** [comment]
I think it would make sense to put this into Bitswap. Though I'm not sure if that will be easy (the way Bitswap works today). I don't have usable code for this.

**Comment by diasdavid** [comment]
This already exists on Bitswap. We need it here to trickle it down. This is needed for https://github.com/ipfs/js-ipfs/pull/856 and should be quick to implement

I made a graph to explain today's architecture.

**Comment by diasdavid** [comment]
@vmx this is labeled as P0 Critical since Jun 4, it should be a simple change. Do you disagree with the priority? Feel free to adjust the label.

**Comment by vmx** [comment]
@diasdavid This slipped my attention, I'll have a look. thanks for pinging.

**Comment by diasdavid** [comment]
@vmx develop the habit at checking the waffle board and use filters to help you understand what is top priority (and also to communicate to others). https://waffle.io/ipld/js-ipld

## https://waffle.io/ipld/js-ipld?label=P0%20-%20Critical

<img width="1607" alt="image" src="https://user-images.githubusercontent.com/1211152/48078538-8f211000-e1e1-11e8-99ea-2cf05779bf66.png">

## https://waffle.io/ipld/js-ipld?label=P1%20-%20High

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/1211152/48078555-99430e80-e1e1-11e8-9b69-fdb60a8c0840.png">
