### ISSUE TITLE
ipld.get() should never give the direct result of resolver.util.deserialize()

### ISSUE THREAD

**Issue by Mr0grog** [ipld/js-ipld#142]
Calling `ipld.get()` should never result in the direct, deserialized value from a resolver’s `util.deserialize()` function. It should instead result in the equivalent of *resolving* the path `/` if no path is provided.

Right now, we explicitly return the result of `resolver.util.deserialize(rawBlockData)` if no path is specified: https://github.com/ipld/js-ipld/blob/c81882e82cdc3985a24b639f1034249988c1da37/src/index.js#L138-L148

(where `ipld._get(cid)` is just a wrapper for `getResolverForCid(cid).util.deserialize(rawData)`)

Instead, we should *always* call `resolver.resolver.resolve(rawBlockData, path)` as part of `ipld.get()`, and the `path` we pass to the resolver should be `/` if no path was specified as an argument to `ipld.get()`.

This is because `get()` should always return an object where the keys reflect paths that could be resolved — i.e. the *IPLD* focused concept of the DAG node, not some other underlying representation, like a `BitcoinjsBlock` from the Bitcoin library, for example. See the discussion in #141 for more about this.

**Comment by vmx** [comment]
With version 0.23 that's the case now. Though `get()` might have additional methods attached. This means that `get()` possible returns a superset of `resolve('/')` (or the same).
