### ISSUE TITLE
Remove dependency on js-ipfs-block-service

### ISSUE THREAD

**Issue by vmx** [ipld/js-ipld#149]
The [BlockService](https://github.com/ipfs/js-ipfs-block-service) is an intermediate abstraction/interface that's not really needed. It makes sure that blocks are retrieved from remote Peers if an Exchange (i.e. Bitswap) is defined. Bitswap already checks by itself if the data is locally available, hence we don't need the BlockService, but we can use Bitswap directly.

JS-IPLD doesn't even need a full [JS Repo implementation](https://github.com/ipfs/js-ipfs-repo), but only the block storage part of it. This means that IPLD could be initialised with just the block store, which doesn't even need to implement the full [datastore interface](https://github.com/ipfs/interface-datastore#readme), but only the part the block API is using (currently `put()`, `get()`, `getMany()` and `delete()`).
So passing in a something that implements the block API subset of the datastore interface is enough.

Steps to get rid of the BlockService

 1. Implement the [datastore interface](https://github.com/ipfs/interface-datastore#readme) for Bitswap which implements the subset to make it usable as block API datastore.
 2. Change the IPLD API to use the a block API datastore instead of a full Repo implementation
 3. Make IPLD use the Bitswap based datastore

@diasdavid Can you please confirm that I'm not missing something here?

**Comment by diasdavid** [comment]
I can't see why this needs to be redesigned or refactored at the moment. The Block Service is designed to give a single API over multiple blockstores, these can be local (e.g. repo) or networked ones (e.g. Bitswap). Today it is a pretty light shim.

> Implement the datastore interface for Bitswap which implements the subset to make it usable as block API datastore.

No go. The datastore is purposefully a key-value store only, it is not a content addressed store.

> Change the IPLD API to use the a block API datastore instead of a full Repo implementation
Make IPLD use the Bitswap based datastore

No. The datastore should continue being the key-value store that it is. This proposed change would soon force the datastore to have to start to understand graphs too for when selectors come into play.

**Comment by vmx** [comment]
Closed as "won't fix".
