### ISSUE TITLE
Move inMemory resolver to separate package

### ISSUE THREAD

**Issue by alanshaw** [ipld/js-ipld#151]
Removes dependence on `ipfs-repo` and `ipfs-block-service`.

**Comment by diasdavid** [comment]
That feature was to make @nicola but I don't believe he ever used it. I believe you can take it out entirely

**Comment by vmx** [comment]
i find it quite useful, yet to trivial to create a separate package for it. What do you think of putting it into an example for js-ipld. This way the code can easily be copy&paste re-used.

**Comment by diasdavid** [comment]
@vmx sounds great!

**Comment by alanshaw** [comment]
SGTM
