### ISSUE TITLE
DAGNodes stored with v1 CIDs are returned with v0 CIDs

### ISSUE THREAD

**Issue by achingbrain** [ipld/js-ipld#157]
This test fails (add to the suite in `test/ipld-dag-pb.js`):

```javascript
it('should return a v1 CID for a DAGNode created with a v1 CID', (done) => {
  dagPB.DAGNode.create(Buffer.from([0, 1, 2, 3]), (err, node) => {
    expect(err).to.not.exist()

    const cid = new CID(node.multihash).toV1()

    resolver.put(node, {
      cid,
      format: cid.codec
    }, (error, nodeCid) => {
      expect(error).to.not.exist()
      expect(nodeCid instanceof CID).to.be.true()
      expect(nodeCid).to.deep.equal(cid)

      resolver.get(nodeCid, (error, result) => {
        expect(error).to.not.exist()
        expect(result.value).to.deep.equal(node)

        done()
      })
    })
  })
})
```

If you remove the `toV1()` conversion it passes.

**Comment by vmx** [comment]
This test passes for me if I add a `const CID = require('cids')`.

**Comment by vmx** [comment]
Though it certainly returns a returns a CID v0. What would you expect? That `js-ipld` always returns a v1 CID?

**Comment by achingbrain** [comment]
If I specify a `cid` as an option to `resolver.put(node, { cid }, cb)`, I would expect the returned `cid` to equal the `cid` I specify, unless `node` is not addressable via that `cid` in which case an error should be passed to the callback.

If I then call `resolver.get(cid, cb)` I would expect the returned node to have the same `cid` that I used to `get` it.

So if I use a v1 CID with `resolver.put`, the returned CID should be the same v1 CID, and I should be able to then use it with `resolver.get` to retrieve the node I previously passed to `resolver.put`.

Similarly if I used a v0 CID, I should get a v0 CID back.  I should not use a v1 CID then have it downgraded to a v0 CID by some part of the IPLD internals.

Not sure why adding the `require` would affect the test.

**Comment by achingbrain** [comment]
Really I'm not sure why I can pass a CID in as an option at all, it should just retrieve or calculate it from the passed node with a `cidVersion`, `codec` etc options, but that's another discussion.

**Comment by vmx** [comment]
Thanks a lot for the detailed reply. I think it totally makes sense and I think the IPLD layer should handle that properly.

**Comment by vmx** [comment]
@achingbrain I had another look. As I said the test doesn't fail for me and seems to do what I expect. I'll try to make it clearer with commenting the code:

```JavaScript
it('should return a v1 CID for a DAGNode created with a v1 CID', (done) => {
  dagPB.DAGNode.create(Buffer.from([0, 1, 2, 3]), (err, node) => {
    // `node` is a `DagNode` object, internally it has a CIDv0.
    // That sounds fine to me.
    expect(err).to.not.exist()

    const cid = new CID(node.multihash).toV1()

    resolver.put(node, {
      cid,
      format: cid.codec
    }, (error, nodeCid) => {
      // `nodeCid` is a CIDv1. So it is as expect, you put the node with
      // a CIDv1 and result is also a CIDv1.
      // BTW, if you pass in a CIDv0, the result will be a CIDv0.
      expect(error).to.not.exist()
      expect(nodeCid instanceof CID).to.be.true()
      expect(nodeCid).to.deep.equal(cid)

      resolver.get(nodeCid, (error, result) => {
        // `result.value` contains a `DagNode` object.
        // In there the CID is a CIDv0. I think that is fine as you
        // don't have public access to the CID anyway.
        expect(error).to.not.exist()
        expect(result.value).to.deep.equal(node)

        done()
      })
    })
  })
})
```

Should any of the behaviour be changed?

**Comment by achingbrain** [comment]
DAGNodes don't have `.cid`/`.multihash` properties any more so this is not a problem any more.
