### ISSUE TITLE
Pass options into the constructor

### ISSUE THREAD

**Issue by vmx** [ipld/js-ipld#161]
Currently the IPLD constructor is taking a `BlockService` object. Change the API to take it an options object (similar to what [libp2p is doing](https://github.com/libp2p/js-libp2p/tree/3226632d83e8684e32b00eeb398b21158b94586d#create-a-node---new-libp2pnodeoptions)).

This makes it possible to pass in the IPLD Formats that should be used. It will include `ipld-dag-cbor` and `ipld-dag-pb` by default and make others optional. This way the Browser bundle size will shrink a lot.

**Comment by diasdavid** [comment]
Done https://github.com/ipld/js-ipld#ipld-constructor. Thanks @vmx :)
