### ISSUE TITLE
Pass CID into `util.deserialize`?

### ISSUE THREAD

**Issue by achingbrain** [ipld/js-ipld#173]
Right now when deserializing data we only pass the block's data into the [`util.deserialize` function of the codec](https://github.com/ipld/js-ipld/blob/master/src/index.js#L325).

If the deserialized version of the data needs to be aware of it's own CID, it must then derive it from the passed data.  For example [`ipld-dag-pb` does this](https://github.com/ipld/js-ipld-dag-pb/blob/master/src/dag-node/create.js#L41-L55).

This has a few side effects:

1.  It's inefficient (this takes about 11% of CPU time when using `ipfs-npm`)
2. It's unnecessary when we have the CID further up the call stack
3. It's inaccurate as the CID version/hash-alg is lost so `ipld-dag-pb` defaults to `sha2-256` which might not be what was used when the DAGNode was originally encoded thus resulting in a different CID

We could pass the CID into `util.deserialize` instead which would negate all of the above points.

Thoughts @ipld/javascript-team ?

**Comment by achingbrain** [comment]
This is where the 11% figure comes from (just doing an `ipfs-npm install` on the `js-ipfs` project):

![image](https://user-images.githubusercontent.com/665810/47735067-9e451280-dc63-11e8-80e5-71f090e4097c.png)

**Comment by vmx** [comment]
@achingbrain: is the problem the serialisation or the calculation of the hash?

I'm asking as if the problem is the serialisation, you could calculate the hash within `util.deserialize()` and pass it into `DAGNode.create()`.

This sounds really dag-pb specific. Normally I wouldn't expect that deserialised formats know (or care) about their serialised hash. Hence I'm hesitant to change the [IPLD Formats interface](https://github.com/ipld/interface-ipld-format) just for that.

**Comment by achingbrain** [comment]
The problem is calculating the hash - it's expensive and without knowing the hashing algorithm used to create the CID, potentially inaccurate.

It's specific to any IPLD datatype that needs to know about it's CID, of which dag-pb happens to be one.  In general I don't think we can predict which data types need to know about their CID and which don't.

**Comment by achingbrain** [comment]
Unless we remove the cid/multihash from ipld-dab-pb I guess? Considering since CIDv1 there’s No guarantee it’s actually correct..

**Comment by vmx** [comment]
I'd argue that none of the IPLD datatypes should know about its CID as as you mention it depends on the hashing algorithm. The deserialised should be independent of that.

So dag-pb is a special case and we also know the hashing algorithm. This leaves us with the problem that calculating it needlessly is a performance hit.

I don't know much about the history of `DAGNode()`, would there be a chance to remove the the need that DAGNode has the multihash? Or perhaps lazy-loading it (in the sense of, it could be added later on, if it's not there it's calculated on the fly)?

**Comment by achingbrain** [comment]
Maybe tomorrow I’ll try removing it and see what happens.

**Comment by achingbrain** [comment]
This was fixed by ipld/js-ipld-dag-pb#99
