### ISSUE TITLE
Typings for typescript users?

### ISSUE THREAD

**Issue by jeffkhull** [ipld/js-ipld#296]
I was wondering if the team has plans to publish typings for this library, for users writing typescript?  If the authors are familiar with typescript, of course the code could be sent through the transpiler to get typings for free.  Just wondering since typescript has gained so much momentum in the JS community :-)

**Comment by vmx** [comment]
Currently a lot of development for IPLD related things happen at https://github.com/multiformats/js-multiformats which we also recommend for new IPLD related developments. That one has TypeScript types defined.
