### ISSUE TITLE
ipld resolver serializes data more time then nessicary

### ISSUE THREAD

**Issue by wanderer** [ipld/js-ipld#63]
It first serialization the data to create the CID then [once again to store the data](https://github.com/ipld/js-ipld-resolver/blob/master/src/index.js#L115).

**Comment by wanderer** [comment]
for now im getting around this by directly interacting with the [blockservice](https://github.com/wanderer/merkle-trie/blob/master/store.js#L28-L31)

**Comment by diasdavid** [comment]
@vmx getting this on your radar :)

**Comment by richardschneider** [comment]
https://github.com/ipld/interface-ipld-format/issues/32 should resolve this issue. 

Can we close this?

**Comment by vmx** [comment]
Can be closed once https://github.com/ipld/interface-ipld-format/issues/32 is closed. Until then it's an open issue.

**Comment by diasdavid** [comment]
@vmx if this one is `P0`, then  ipld/interface-ipld-format#32 should be as well

**Comment by vmx** [comment]
`cid()` is now taking the serialized version of the data, hence it is fixed.
