### ISSUE TITLE
IPLD resolver API changes

### ISSUE THREAD

**Issue by kumavis** [ipld/js-ipld#70]
We've discussed some potential changes for ipld-resolver. I wanted to make sure we're tracking them all.

- [x] get paths only / lazy value lookups ( some objects like etherum-tx's have implicit data (e.g.: `fromAddress`) that is computed via expensive crypto - we should only return values that were explicitly asked for)
- [ ] get external / local paths only
- [ ] toJSON + fromJSON - roundtrip (de-)serialize data via json format
- [x] put + patch api https://github.com/ipld/js-ipld-resolver/issues/66
- [ ] text summary - output text that explains the content of a given ipfs-block
- [x] globbing ( this should be handled outside of the resolvers )

**Comment by nicola** [comment]
@kumavis are you also implementing globbing? See here: https://github.com/ipld/specs/issues/35#issuecomment-277246574 !

I have a soon-to-be-optimized expensive implementation here: https://github.com/nicola/js-ipld-selector -let me know if you are working on it too, so that we can sync!

**Comment by kumavis** [comment]
I'm not implementing any of these, they were more like discussion items that I wanted written down somewhere

**Comment by diasdavid** [comment]
>  get external / local paths only

@kumavis remind me what you mean by that

>  toJSON + fromJSON - roundtrip (de-)serialize data via json format

We can do .toJSOn https://github.com/ipld/interface-ipld-format/issues/10

> text summary - output text that explains the content of a given ipfs-block

Is this for CLI type applications? Could you give examples for the existing formats? Is this like having a .toTXT? Could this be achieved just by using the .toJSON?
