### ISSUE TITLE
Support for Bitcoin

### ISSUE THREAD

**Issue by diasdavid** [ipld/js-ipld#88]
Currently, the js implementation is missing git and Bitcoin support to match the go-ipfs implementation

![image](https://user-images.githubusercontent.com/1211152/28090188-5a55aab4-6683-11e7-8582-7ef15e9b53a2.png)
http://ipld.io/implementations/

We will get to this at some point, however, if there is someone in the community that would like to take on that task right now, it would be really appreciated! Let me know if you need help getting started :)

**Comment by Kubuxu** [comment]
Supporting Git isn't that easy, there is quite a bit of delicate parsing there. @magik6k who implemented Go's support for git might be of help.

**Comment by diasdavid** [comment]
@magik6k would you like to tackle this one?

**Comment by magik6k** [comment]
Sure, might have a look at that

**Comment by diasdavid** [comment]
@magik6k awesome work adding support for Git in JS land <3

**Comment by diasdavid** [comment]
- [x] Git thanks to @magik6k 👏🏽 ✅
- [ ] Missing Bitcoin

**Comment by vmx** [comment]
Bitcoing is also done: https://github.com/ipld/js-ipld-bitcoin
