### ISSUE TITLE
Improve IPLD Performance

### ISSUE THREAD

**Issue by daviddias** [ipld/js-ipld#94]
? Following the discussion on the first IPLD deep dive -- https://github.com/ipfs/pm/issues/484 --

@wanderer has volunteered to our Captain of Performance Testing 🙌🏽 🌟 ⚡️ Thank you! ❤️

@wanderer has already been developing benchmarks for IPLD and doing a lot of work with IPLD (e.g https://github.com/ipld/js-ipld-graph-builder) and identified some serious performance issues such as: https://github.com/ipld/interface-ipld-format/issues/7.

The ideal goal is reach a state where IPLD has a set of powerful benchmarks for multiple use cases and the right primitives that let the user tune for its use case, as I believe that finding a one size fits all solution is going to be hard (thinking of the caching question). That being said, we do have a lot of work to do just in raising the bar and that will improve perf for all use cases.

Another great endeavour related to this one is the development of WASM resolvers and hashing functions so that we can go at max speed we could go in a Browser/Node.js env. Crypto operations are some of the primary perf bottlenecks of the whole js-ipfs.

**Comment by vmx** [comment]
I'm closing this issue as it is kind of a meta issue. Of course better performance is always good, but it's not a major concern at the moment. The focus is on getting the APIs and abstractions right. Hence closing this issue.
