### ISSUE TITLE
ipld-format spec upgrade - .cid(node) => .cid(serializedNode)

### ISSUE THREAD

**Issue by diasdavid** [ipld/js-ipld#95]
As pointed out by @wanderer here https://github.com/ipld/interface-ipld-format/issues/7, we need to update the spec. I'm using this issue to track of the work that needs to happen.

Edit: Moved tracking info to https://github.com/ipld/js-ipld-resolver/pull/96

**Comment by diasdavid** [comment]
Let's also do this as part of this task:
- [ ] https://github.com/ipld/js-ipld-ethereum/issues/4

**Comment by vmx** [comment]
This change got merged into the spec with https://github.com/ipld/interface-ipld-format/pull/24. The tracking issue for the implementation is: https://github.com/ipld/interface-ipld-format/issues/32.

I'm closing this one, follow the implementation issue instead.
